Bump dependencies
wikimedia/svgtranslate pull request #346
Opened 2020-09-18 03:37 UTC by MusikAnimal

Also adds symfony/mime, which was apparently unbundled from some other
Symfony package.

Bug: T262464

2020-09-18 07:06 UTC, samwilson requested changes
The ULS dialog isn't working for me with this patch and shows the error "Uncaught TypeError: targetLangButton.$element.uls is not a function". It might be because I'm not building things correctly, but I don't think so. The error I'm getting the same one described in https://phabricator.wikimedia.org/T233182

Also, webpack is giving the following warning:

> WARNING   Webpack Encore requires version ^6.2.0 of less-loader, but your version (4.1.0) is too old. > The related feature will probably *not* work correctly.

2020-09-18 20:07 UTC, MusikAnimal commented
> The ULS dialog isn't working for me with this patch and shows the error "Uncaught TypeError: targetLangButton.$element.uls is not a function". It might be because I'm not building things correctly, but I don't think so. The error I'm getting the same one described in https://phabricator.wikimedia.org/T233182
> 
> Also, webpack is giving the following warning:
> 
> > WARNING   Webpack Encore requires version ^6.2.0 of less-loader, but your version (4.1.0) is too old. > The related feature will probably _not_ work correctly.

Ah, I obviously didn't test the language selector! I tried all sorts of combinations of packages, such as locking the old version of jQuery, ULS, OOUI and Webpack, but was still running into this issue. So for now this PR is just for PHP dependencies. Note also have a lot of deprecation notices now, but I assume those can be ironed out in a future PR.

2020-09-19 00:36 UTC, samwilson reviewed
I don't know if it matters, but this can be rebased.

2020-09-19 00:36 UTC, samwilson commented on composer.json
> +        "wikimedia/toolforge-bundle": "^0.19"
This can be `^1.0` now. :)

2020-09-21 06:00 UTC, merged